
2021-09-16 19:32:59,379 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:512]
2021-09-16 19:33:21,079 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:512]
2021-09-16 19:33:26,560 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:512]
2021-09-16 19:35:38,066 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:512]
2021-09-16 19:35:48,902 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:512]
2021-09-17 14:51:06,493 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:512]
2021-09-17 14:51:27,738 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 223, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 14:51:29,565 ERROR: Exception on /artists/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 416, in create_artist_form
    form = ArtistForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 14:51:34,921 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 223, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 14:51:39,491 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 223, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 14:51:55,722 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 223, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 14:51:57,256 ERROR: Exception on /artists/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 416, in create_artist_form
    form = ArtistForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 14:52:33,532 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:512]
2021-09-17 14:52:45,932 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 223, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 14:52:49,370 ERROR: Exception on /artists/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 416, in create_artist_form
    form = ArtistForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 14:52:50,969 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 223, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 14:53:14,247 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 223, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 14:53:21,501 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:512]
2021-09-17 14:53:23,266 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 223, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 14:53:29,669 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 223, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 14:55:20,939 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:512]
2021-09-17 14:55:25,118 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 223, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 14:57:44,172 ERROR: Exception on /artists/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 416, in create_artist_form
    form = ArtistForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 15:00:08,713 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:512]
2021-09-17 15:00:16,473 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 223, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 15:00:23,280 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 223, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 15:06:28,742 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 223, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 15:06:30,365 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 223, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 15:06:33,803 ERROR: Exception on /artists/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 416, in create_artist_form
    form = ArtistForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 15:06:35,357 ERROR: Exception on /shows/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 480, in create_shows
    form = ShowForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 15:08:55,626 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 223, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 15:11:12,042 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 223, in create_venue_form
    #  Create Venue
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 15:12:48,671 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:518]
2021-09-17 15:13:10,468 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 229, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 15:14:16,260 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 229, in create_venue_form
    return render_template('forms/new_venue.html', form=form)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 15:18:44,607 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:517]
2021-09-17 15:18:57,937 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 228, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 15:19:01,527 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 228, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 15:19:04,954 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 228, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 15:20:19,313 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 228, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 15:20:32,195 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 228, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 15:23:19,121 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 228, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 15:28:11,090 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:517]
2021-09-17 15:28:18,243 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 228, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 15:39:27,709 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:517]
2021-09-17 15:39:38,427 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 228, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 15:58:00,098 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:517]
2021-09-17 15:58:19,552 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 228, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 16:00:03,269 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:519]
2021-09-17 16:00:11,577 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 230, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 16:05:27,798 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:525]
2021-09-17 16:05:42,574 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 236, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 16:09:24,624 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:525]
2021-09-17 16:09:48,240 ERROR: Exception on /artists/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 429, in create_artist_form
    form = ArtistForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 16:09:50,762 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 236, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 16:11:35,138 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 236, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 16:27:32,693 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:527]
2021-09-17 16:28:10,335 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 875, in import_string
    return getattr(module, obj_name)
AttributeError: module 'config' has no attribute 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 877, in import_string
    raise ImportError(e)
ImportError: module 'config' has no attribute 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 236, in create_venue_form
    app.config.from_object('config.settings')
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\config.py", line 161, in from_object
    obj = import_string(obj)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 881, in import_string
    raise ImportStringError(import_name, e).with_traceback(sys.exc_info()[2])
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 877, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'config.settings'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' found in 'C:\\Users\\willi\\Documents\\Workspace\\Udacity\\Projekte\\01_fyyur\\config.py'.
- 'config.settings' not found.

Original exception:

ImportError: module 'config' has no attribute 'settings'
2021-09-17 16:31:20,796 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 875, in import_string
    return getattr(module, obj_name)
AttributeError: module 'config' has no attribute 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 877, in import_string
    raise ImportError(e)
ImportError: module 'config' has no attribute 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 236, in create_venue_form
    app.config.from_object('config.settings')
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\config.py", line 161, in from_object
    obj = import_string(obj)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 881, in import_string
    raise ImportStringError(import_name, e).with_traceback(sys.exc_info()[2])
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 877, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'config.settings'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' found in 'C:\\Users\\willi\\Documents\\Workspace\\Udacity\\Projekte\\01_fyyur\\config.py'.
- 'config.settings' not found.

Original exception:

ImportError: module 'config' has no attribute 'settings'
2021-09-17 16:31:37,629 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 875, in import_string
    return getattr(module, obj_name)
AttributeError: module 'config' has no attribute 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 877, in import_string
    raise ImportError(e)
ImportError: module 'config' has no attribute 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 236, in create_venue_form
    app.config.from_object('config.settings')
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\config.py", line 161, in from_object
    obj = import_string(obj)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 881, in import_string
    raise ImportStringError(import_name, e).with_traceback(sys.exc_info()[2])
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 877, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'config.settings'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' found in 'C:\\Users\\willi\\Documents\\Workspace\\Udacity\\Projekte\\01_fyyur\\config.py'.
- 'config.settings' not found.

Original exception:

ImportError: module 'config' has no attribute 'settings'
2021-09-17 16:31:45,035 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 875, in import_string
    return getattr(module, obj_name)
AttributeError: module 'config' has no attribute 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 877, in import_string
    raise ImportError(e)
ImportError: module 'config' has no attribute 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 236, in create_venue_form
    app.config.from_object('config.settings')
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\config.py", line 161, in from_object
    obj = import_string(obj)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 881, in import_string
    raise ImportStringError(import_name, e).with_traceback(sys.exc_info()[2])
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 877, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'config.settings'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' found in 'C:\\Users\\willi\\Documents\\Workspace\\Udacity\\Projekte\\01_fyyur\\config.py'.
- 'config.settings' not found.

Original exception:

ImportError: module 'config' has no attribute 'settings'
2021-09-17 16:34:32,847 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:524]
2021-09-17 16:34:38,070 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 235, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-09-17 16:35:02,925 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:527]
2021-09-17 16:35:08,678 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 875, in import_string
    return getattr(module, obj_name)
AttributeError: module 'config' has no attribute 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 877, in import_string
    raise ImportError(e)
ImportError: module 'config' has no attribute 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 236, in create_venue_form
    app.config.from_object('config.settings')
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\config.py", line 161, in from_object
    obj = import_string(obj)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 881, in import_string
    raise ImportStringError(import_name, e).with_traceback(sys.exc_info()[2])
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 877, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'config.settings'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' found in 'C:\\Users\\willi\\Documents\\Workspace\\Udacity\\Projekte\\01_fyyur\\config.py'.
- 'config.settings' not found.

Original exception:

ImportError: module 'config' has no attribute 'settings'
2021-09-17 16:35:30,024 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:527]
2021-09-17 16:35:34,532 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 875, in import_string
    return getattr(module, obj_name)
AttributeError: module 'config' has no attribute 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 877, in import_string
    raise ImportError(e)
ImportError: module 'config' has no attribute 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 236, in create_venue_form
    app.config.from_object('config.settings')
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\config.py", line 161, in from_object
    obj = import_string(obj)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 881, in import_string
    raise ImportStringError(import_name, e).with_traceback(sys.exc_info()[2])
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 877, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'config.settings'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' found in 'C:\\Users\\willi\\Documents\\Workspace\\Udacity\\Projekte\\01_fyyur\\config.py'.
- 'config.settings' not found.

Original exception:

ImportError: module 'config' has no attribute 'settings'
2021-09-17 16:35:45,442 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:527]
2021-09-17 16:36:16,364 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 875, in import_string
    return getattr(module, obj_name)
AttributeError: module 'config' has no attribute 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 877, in import_string
    raise ImportError(e)
ImportError: module 'config' has no attribute 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 236, in create_venue_form
    app.config.from_object('config.settings')
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\config.py", line 161, in from_object
    obj = import_string(obj)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 881, in import_string
    raise ImportStringError(import_name, e).with_traceback(sys.exc_info()[2])
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 877, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'config.settings'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' found in 'C:\\Users\\willi\\Documents\\Workspace\\Udacity\\Projekte\\01_fyyur\\config.py'.
- 'config.settings' not found.

Original exception:

ImportError: module 'config' has no attribute 'settings'
2021-09-17 16:36:33,580 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 875, in import_string
    return getattr(module, obj_name)
AttributeError: module 'config' has no attribute 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 877, in import_string
    raise ImportError(e)
ImportError: module 'config' has no attribute 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 236, in create_venue_form
    #app.config.from_object('config.settings')
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\config.py", line 161, in from_object
    obj = import_string(obj)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 881, in import_string
    raise ImportStringError(import_name, e).with_traceback(sys.exc_info()[2])
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\werkzeug\utils.py", line 877, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'config.settings'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' found in 'C:\\Users\\willi\\Documents\\Workspace\\Udacity\\Projekte\\01_fyyur\\config.py'.
- 'config.settings' not found.

Original exception:

ImportError: module 'config' has no attribute 'settings'
2021-09-17 16:37:27,856 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:523]
2021-09-17 16:37:31,701 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 235, in create_venue_form
    return render_template('forms/new_venue.html', form=form)
NameError: name 'form' is not defined
2021-09-17 16:37:59,431 INFO: errors [in C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py:524]
2021-09-17 16:38:04,657 ERROR: Exception on /venues/create [GET] [in C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\willi\Documents\Workspace\Udacity\Projekte\01_fyyur\app.py", line 235, in create_venue_form
    form = VenueForm()
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\willi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask_wtf\csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
